Create Linear Search.11.14.23.14:00
Фридман, Лекс
Материал из Википедии — свободной энциклопедии
Текущая версия страницы пока не проверялась опытными участниками и может значительно отличаться от версии, проверенной 19 февраля 2023 года; проверки требуют 18 правок.

Эту статью предлагается удалить.
Пояснение причин и соответствующее обсуждение вы можете найти на странице Википедия:К удалению/17 января 2023.
Пока процесс обсуждения не завершён, статью можно попытаться улучшить, однако следует воздерживаться от переименований или немотивированного удаления содержания, подробнее см. руководство к дальнейшему действию.
Не снимайте пометку о выставлении на удаление до подведения итога обсуждения.
Последнее изменение сделано участником 2600:4040:A6CA:2000:188C:C3D:6C02:112F (журналы) в 02:01, 13 ноября 2023 (UTC; около 2 дней назад).
Лекс Фридман

Дата рождения	15 августа 1983 (40 лет)
Место рождения	
Чкаловск, Ленинабадская область, Таджикская ССР, СССР[1]
Страна	
 США
Род деятельности	специалист в области информатики, исследователь искусственного интеллекта, подкастер, исследователь
Отец	Alexander A. Fridman[d]
Сайт	lexfridman.com (англ.)
Логотип Викисклада Медиафайлы на Викискладе
В Википедии есть статьи о других людях с фамилией Фридман.
Лекс Фридман (Lex Fridman, имя при рождении Алексей Федотов) — американский ученый[2], интервьюер и блогер русского и еврейского происхождения. Область его научных исследований — компьютерные технологии и искусственный интеллект[3]. Среди его гостей на YouTube канале — Илон Маск [4], Гвидо ван Россум, Марк Цукерберг [5], Джордан Питерсон, Виталий Бутерин, Оливер Стоун, Сэм Олтмэн, Илья Суцкевер, Канье Уэст [6], Джо Роган [7][8] и другие.[9][10] Общее количество просмотров видеоблога Фридмана на Youtube составляет почти пол миллиарда просмотров [11] Подкаст Фридмана включен в список 17-ти технических подкастов, рекомендуемых экспертами Forbes [12]


Содержание
1	Биография
2	Факты
3	Примечания
4	Ссылки
Биография
Родился в Чкаловске Таджикская АССР 15 августа 1983 года, под именем Алексей Федотов. До подросткового возраста рос и учился в Москве. Его отец Александр Аркадьевич Фридман, физик, профессор и директор Института плазмы Университетa Дрекселя[13], индекс Хирша 98[14], родился в Киеве. Мать росла в Харькове. Родители имеют еврейские и русские корни. Переехал в Чикаго вместе с родителями и братом из Москвы в 1994 году, в возрасте 11 лет. Получил степень PhD в компьютерной инженерии в 2014 году.[15] Имеет брата, Григория Федотова (Фридмана), являющегося исследователем физики плазмы.

В 2018 году начал вести подкаст, который быстро обрел популярность и стал одним из наиболее популярных технических подкастов в США.

Увлекается MMA и бразильским джиу-джитсу, имеет черный пояс. В одном из выпусков подкаста боролся с Марком Цукербергом.

Факты
После начала Украинского конфликта заявил, что в равной степени считает русских, украинцев и американцев своими народами и будет популяризировать их культуры, не поддаваясь давлению ни одной из сторон. Заявил, что однозначно осуждает любые военные действия (подчеркнув, что также осуждает вторжения США в другие страны), но избегает прямого осуждения любой из сторон, возлагая вину за трагедию на отдельных политиков, а не на народы в целом. Утверждает, что во всем старается придерживаться взвешенной и независимой позиции.

По словам Фридмана, часть его семьи погибла во время Холокоста [6]

Помогал Илону Маску в тренировках по джиу-джитсу [16]

Чисто говорит по-русски. Нередко цитирует Пастернака и Достоевского.

Примечания
 https://lexfridman.com/jimmy-wales-transcript/
 Black, Julia Peace, love, and Hitler: How Lex Fridman's podcast became a safe space for the anti-woke tech elite (амер. англ.). Business Insider. Дата обращения: 6 августа 2023.
 A, David Lex Fridman Podcast: A Look At The Popularity And Influence Of The Podcast (амер. англ.). www.netinfluencer.com (22 ноября 2022). Дата обращения: 6 августа 2023.
 Who is Lex Fridman? Elon Musk's friend who wants to work for free as Twitter head (англ.). Business Today (20 декабря 2022). Дата обращения: 6 августа 2023.
 inc.com.
 https://www.latimes.com/people/august-brown; https://www.latimes.com/people/anousha-sakoui Kanye West assails Jews, abortion in new interview with Lex Fridman (амер. англ.). Los Angeles Times (25 октября 2022). Дата обращения: 6 августа 2023.
 ‘I Don’t Want to Help Him’: Joe Rogan Says He Refused Trump as a Podcast Guest (Published 2022) (англ.) (6 July 2022). Дата обращения: 6 августа 2023.
 Saul, Derek Don't Be Surprised Joe Rogan Said He Doesn't Like Trump—Breaking Down Their Complicated History (англ.). Forbes. Дата обращения: 6 августа 2023.
 Lex Fridman (англ.).
 Nathan J. Robinson. The Guy Who Just Loves Everyone (англ.) // Current Affairs. — 2023-01-05. — ISSN 2471-2647.
 Lex Fridman - YouTube. www.youtube.com. Дата обращения: 6 августа 2023.
 Panel®, Expert Council Post: 17 Tech Pros Share Their Favorite Industry-Focused Podcasts (англ.). Forbes. Дата обращения: 6 августа 2023.
 Nyheim Plasma Institute
 Alexander Fridman on Google Scholar
 Lex Fridman (англ.) // Wikipedia. — 2023-01-06.
 Syme, Pete Elon Musk is getting ready for his potential fight with Mark Zuckerberg by training martial arts with podcaster Lex Fridman (амер. англ.). Business Insider. Дата обращения: 6 августа 2023.
Ссылки
Lex Fridman on Google Scholar
Перейти к шаблону «Внешние ссылки»  Перейти к элементу Викиданных  В социальных сетях
ТвиттерFacebookInstagramLinkedIn
Фото, видео и аудио	
YouTube
Тематические сайты	
GitHubGoogle ScholarМатематическая генеалогияORCIDResearchGateScopusMusicBrainz
В библиографических каталогах	
ISNI: 0000 0005 0801 2652
Категории: Родившиеся 15 августаРодившиеся в 1983 годуРодившиеся в Бустоне (город)Персоналии по алфавитуБлогеры США
Навигация
Вы не представились системе
Обсуждение
Вклад
Создать учётную запись
Войти
СтатьяОбсуждение
ЧитатьТекущая версияПравитьПравить кодИсторияПоиск
Искать в Википедии
Заглавная страница
Содержание
Избранные статьи
Случайная статья
Текущие события
Пожертвовать
Участие
Сообщить об ошибке
Как править статьи
Сообщество
Форум
Свежие правки
Новые страницы
Справка
Инструменты
Ссылки сюда
Связанные правки
Служебные страницы
Постоянная ссылка
Сведения о странице
Цитировать страницу
Получить сокращённый URL-адрес
Печать/экспорт
Скачать как PDF
Версия для печати
В других проектах
Викисклад
Элемент Викиданных

На других языках
Deutsch
English
Español
فارسی
Français
Italiano
Português
Svenska
Türkçe
Ещё 7
Править ссылки
Эта страница в последний раз была отредактирована 13 ноября 2023 в 02:01.
Текст доступен по лицензии Creative Commons «С указанием авторства — С сохранением условий» (CC BY-SA); в отдельных случаях могут действовать дополнительные условия. Подробнее см. Условия использования.
Wikipedia® — зарегистрированный товарный знак некоммерческой организации Фонд Викимедиа (Wikimedia Foundation, Inc.)
Политика конфиденциальностиОписание ВикипедииОтказ от ответственностиСвяжитесь с намиКодекс поведенияРазработчикиСтатистикаЗаявление о кукиМобильная версия........
make a  linear search algorithm:  
Use a loop to get each item
Embed an if statement to compare the item in the current loop position (i) to the search key and return true if there is a match. This will end the loop and the function.
If the loop completes, that means there is no match, so return false....use a 10x10 multiplication table to return the search for a user intput integer
Sure, here is a linear search algorithm that uses a loop to get each item, embeds an if statement to compare the item in the current loop position (i) to the search key and return true if there is a match, and if the loop completes, that means there is no match, so it returns false:

Python
def linear_search(array, target):
    for i, element in enumerate(array):
        if element == target:
            return True

    return False
Use code with caution. Learn more
Here is an example of how to use the linear_search function to search for a number in a multiplication table:

Python
multiplication_table = [[i * j for j in range(1, 11)] for i in range(1, 11)]

target = int(input("Enter a number to search for: "))

if linear_search(multiplication_table, target):
    print("The number", target, "is in the multiplication table.")
else:
    print("The number", target, "is not in the multiplication table.")
Use code with caution. Learn more
profile picture
write the above program in c++
Sure, here is the linear search algorithm written in C++:

C++
#include <iostream>

using namespace std;

bool linear_search(int array[], int size, int target) {
    for (int i = 0; i < size; i++) {
        if (array[i] == target) {
            return true;
        }
    }

    return false;
}

int main() {
    int multiplication_table[10][10];

    for (int i = 1; i <= 10; i++) {
        for (int j = 1; j <= 10; j++) {
            multiplication_table[i - 1][j - 1] = i * j;
        }
    }

    int target;
    cout << "Enter a number to search for: ";
    cin >> target;

    if (linear_search(multiplication_table, 10 * 10, target)) {
        cout << "The number " << target << " is in the multiplication table." << endl;
    } else {
        cout << "The number " << target << " is not in the multiplication table." << endl;
    }

    return 0;
}
Use code with caution. Learn more
profile picture
correct this error ...main.cpp:28:9: error: no matching function for call to 'linear_search'
    if (linear_search(multiplication_table, 10 * 10, target)) {
        ^~~~~~~~~~~~~
main.cpp:5:6: note: candidate function not viable: no known conversion from 'int[10][10]' to 'int *' for 1st argument
bool linear_search(int array[], int size, int target) {
     ^
1 error generated....in this program.....#include <iostream>

using namespace std;

bool linear_search(int array[], int size, int target) {
  for (int i = 0; i < size; i++) {
    if (array[i] == target) {
      return true;
    }
  }

  return false;
}

int main() {
  int multiplication_table[10][10];

  for (int i = 1; i <= 10; i++) {
    for (int j = 1; j <= 10; j++) {
      multiplication_table[i - 1][j - 1] = i * j;
    }
  }

  int target;
  cout << "Enter a number to search for: ";
  cin >> target;

  if (linear_search(multiplication_table, 10 * 10, target)) {
    cout << "The number " << target << " is in the multiplication table." << endl;
  } else {
    cout << "The number " << target << " is not in the multiplication table." << endl;
  }

  return 0;
}
View other drafts







The error occurs because the linear_search function expects an array of integers as its first argument, but you are passing it a two-dimensional array of integers. To fix this, you need to pass the address of the first element in the multiplication table to the linear_search function. Here is the corrected code:

C++
#include <iostream>

using namespace std;

bool linear_search(int array[], int size, int target) {
    for (int i = 0; i < size; i++) {
        if (array[i] == target) {
            return true;
        }
    }

    return false;
}

int main() {
    int multiplication_table[10][10];

    for (int i = 1; i <= 10; i++) {
        for (int j = 1; j <= 10; j++) {
            multiplication_table[i - 1][j - 1] = i * j;
        }
    }

    int target;
    cout << "Enter a number to search for: ";
    cin >> target;

    if (linear_search(&multiplication_table[0][0], 10 * 10, target)) {
        cout << "The number " << target << " is in the multiplication table." << endl;
    } else {
        cout << "The number " << target << " is not in the multiplication table." << endl;
    }

    return 0;
}
Use code with caution. Learn more
This code will pass the address of the first element in the multiplication_table array to the linear_search function. The & operator before multiplication_table[0][0] takes the address of the element.