Create SORTDESCENDING.11.16.23.17::38
ORRECT THE PROGRAM WHERE ....main.cpp:16:18: error: use of undeclared identifier 'SIZE'
    int intArray[SIZE] = {5, 3, 32, -1, 1, 104, 53};
                 ^
main.cpp:21:31: error: use of undeclared identifier 'SIZE'
    sort(intArray, intArray + SIZE, wayToSort);
                              ^
main.cpp:24:26: error: use of undeclared identifier 'SIZE'
    for (int i = 0; i != SIZE; ++i)
                         ^
3 errors generated.   FOR....// Array Sorting Descending Example.
// By Zereo 04/22/13
#include <iostream>
#include <algorithm>
#include <vector>

using namespace std;

// We need this function to define how to sort
// the array. We will pass this function into the
// third parameter and it will tell it to sort descendingly.
bool wayToSort(int i, int j) { return i > j; }

int main()
{
  int intArray[SIZE] = {5, 3, 32, -1, 1, 104, 53};

  //Now we call the sort function
  // Do not include the () when you call wayToSort
  // It must be passed as a function pointer or function object
  sort(intArray, intArray + SIZE, wayToSort);

  cout << "Sorted Array looks like this." << endl;
  for (int i = 0; i != SIZE; ++i)
    cout << intArray[i] << " ";
   
  return 0;
}

1
To fix the errors, you need to define the SIZE constant before using it. Here's the corrected code:

C++
// Array Sorting Descending Example.
// By Zereo 04/22/13

#include <iostream>
#include <algorithm>
#include <vector>

using namespace std;

// We need this function to define how to sort
// the array. We will pass this function into the
// third parameter and it will tell it to sort descendingly.
bool wayToSort(int i, int j) { return i > j; }

int main() {
    const int SIZE = 7; // Define the SIZE constant
    int intArray[SIZE] = {5, 3, 32, -1, 1, 104, 53};

    // Now we call the sort function
    // Do not include the () when you call wayToSort
    // It must be passed as a function pointer or function object
    sort(intArray, intArray + SIZE, wayToSort);

    cout << "Sorted Array looks like this." << endl;
    for (int i = 0; i != SIZE; ++i)
        cout << intArray[i] << " ";
    return 0;
}
Use code with caution. Learn more
Sources
github.com/adityaverma998/stl_used_in_c_plus_plus
profile picture
HOW DOES WAY TO SORT ITERATE THROUGH THE ARRAY AND ALSO MAKE THE COMPARISON OF I BEING GREATER THAN OR LESS THAN J RESULTING IN THE DESCENDING SORT OUTPUT
The wayToSort function is a comparison function that is used by the sort algorithm to determine the order in which the elements of an array should be sorted. The function takes two integer arguments, i and j, and returns true if i is greater than j, and false otherwise.
When the sort algorithm calls the wayToSort function, it passes it two pointers, one to the current element of the array and one to the next element of the array. The function compares the values of the two elements and returns true if the current element is greater than the next element. If the function returns true, the sort algorithm swaps the two elements.
The sort algorithm continues to call the wayToSort function until the array is sorted. The result is an array that is sorted in descending order.
Here is an example of how to use the wayToSort function to sort an array of integers in descending order:

C++
#include <iostream>
#include <algorithm>

using namespace std;

int main() {
  int intArray[] = {5, 3, 32, -1, 1, 104, 53};
  int size = sizeof(intArray) / sizeof(intArray[0]);

  sort(intArray, intArray + size, wayToSort);

  for (int i = 0; i < size; ++i) {
    cout << intArray[i] << " ";
  }

  return 0;
}

bool wayToSort(int i, int j) {
  return i > j;
}
Use code with caution. Learn more
This code will output the following:

104 53 32 5 3 1 -1
As you can see, the array is sorted in descending order.

profile picture
WHERE DOES THE SWAP MECHANISM TAKE PLACE AFTER THE ELEMENTS I AND J ARE COMPARED
View other drafts












The swap mechanism takes place within the sort algorithm itself. The algorithm iterates through the array, comparing each element to the next element using the comparison function that is passed to it. If the comparison function returns true, the algorithm swaps the two elements. This process continues until the entire array is sorted.

The swap operation is typically implemented using a temporary variable. For example, the following code shows how to swap two integers:

C++
int temp = a;
a = b;
b = temp;
Use code with caution. Learn more
This code will swap the values of the two variables a and b. The swap operation is used by the sort algorithm to swap the elements of an array that are out of order.
std::sort
The sort() function in the algorithm header can be a very useful tool to both new and experienced programmers. It's use is to sort containers like arrays and vectors.

The first example is what the function looks like. The second example is an optional overloaded function that includes a third parameter. First take a look at each of these functions and see if we can figure out what each parameter does.

Example 1 ~ std::sort(myvector.begin(), myvector.end())

Example 2 ~ std::sort(myvector.begin(), myvector.end(), myCompFunction)


About The Function
So let’s go dig into these and figure out what each does and why it does it.

Found in ~ #include <algorithm>

Parameter 1 myvector.begin() ~ The first parameter is where you will be putting a iterator(Pointer) to the first element in the range that you want to sort. The sort will include the element that the iterator points to.

Parameter 2 myvector.end() ~ The second parameter is almost like the first but instead of putting a iterator to the first element to sort you will be putting a iterator to the last element. One very important difference is that the search won’t include the element that this iterator points to. It is [First,Last) meaning it includes the first parameter in the sort but it doesn’t include the second parameter in the sort.

Function Return ~ This function doesn’t return anything because it alters the container directly through iterators(Pointers).


Array Example
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
// sort() Example using arrays.
// By Zereo 04/22/13
#include <iostream>
#include <algorithm>

using namespace std;

const int SIZE = 7;

int main()
{
    int intArray[SIZE] = {5, 3, 32, -1, 1, 104, 53};

    //Now we call the sort function
    sort(intArray, intArray + SIZE);

    cout << "Sorted Array looks like this." << endl;
    for (int i = 0; i != SIZE; ++i)
        cout << intArray[i] << " ";

    return 0;
}

Things to know

When we use the sort function to sort an array our arguments will look a bit different then when we use it on a vector for example. In the example above when we pass in intArray as an argument we are telling the function to start the sort at the beginning of the array. If we wanted it to start the sort at the second element of the array we would do sort(intArray + 1, intArray + SIZE);. So when we do intArray + SIZE for the second argument we are telling the array to sort up to the last element in the array.

Using C++11 to simplify things

We can make sorting whole arrays even easier by using std::begin() and std::end(). std::begin() will return a iterator(pointer) to the first element in the array we pass it. Whereas std::end() will return a iterator(pointer) to one past the last element in the array we pass it. So we could call the sort function by passing it begin() and end() like so. To make this line of code work, be sure to #include <algorithm> and using namespace std;

sort(begin(intArray), end(intArray));


 

The Overloaded sort() With A Third Parameter.

The third parameter in the sort() function is actually a very useful feature. It allows us to define how the sort() function will actually perform the search. Sometimes you can get by with the normal version of sort(), but what if we wanted to change how the container was sorted by having it sort by descending order instead of ascending? Or what if we had a container full of a special type of class objects we created and need to sort that container a special way? Well this is where the third parameter comes in.


Making it sort by descending order example.
 

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
// Array Sorting Descending Example.
// By Zereo 04/22/13
#include <iostream>
#include <algorithm>
#include <vector>

using namespace std;

// We need this function to define how to sort
// the array. We will pass this function into the
// third parameter and it will tell it to sort descendingly.
bool wayToSort(int i, int j) { return i > j; }

int main()
{
    int intArray[SIZE] = {5, 3, 32, -1, 1, 104, 53};

    //Now we call the sort function
    // Do not include the () when you call wayToSort
    // It must be passed as a function pointer or function object
    sort(intArray, intArray + SIZE, wayToSort);

    cout << "Sorted Array looks like this." << endl;
    for (int i = 0; i != SIZE; ++i)
        cout << intArray[i] << " ";
    
    return 0;
}

The Function

First let’s look at the function. What we did is we created a function that will determine whether i > j every time it is called. The sort function will automatically assign an element to both i and j.

The function you make needs to have a return type of Boolean.

So when we define bool wayToSort(int i, int j) { return i > j; }, we are saying we wanted it to sort descending because i>j. Whereas ascending would be i<j.


Using the STL to simplify sorting in ascending or descending.

Another solution to the problem of getting it to sort descending is to use std::greater(), which would look like this.

sort(intVec.begin(), intVec.end(), greater<int>());